spring.application.name=rm

spring.thymeleaf.cache=false

#--------------------------------------------------
# Static Resource (CSS/JS cache disable for dev)
#--------------------------------------------------
spring.web.resources.cache.period=0
spring.web.resources.chain.cache=false

#--------------------------------------------------
# File upload Size
#--------------------------------------------------
spring.servlet.multipart.location=/allpack9988/tomcat/upload-dir
spring.servlet.multipart.enabled=true
spring.servlet.multipart.max-file-size=-1
spring.servlet.multipart.max-request-size=-1

#--------------------------------------------------
# MariDB
#--------------------------------------------------
spring.datasource.driverClassName=org.mariadb.jdbc.Driver
spring.datasource.url=jdbc:mariadb://localhost:3306/allpack9988?characterEncoding=UTF-8
#spring.datasource.url=jdbc:mariadb://allpack9988.cafe24.com:3306/allpack9988?characterEncoding=UTF-8
spring.datasource.username=allpack9988
spring.datasource.password=cafe!9988

#--------------------------------------------------
# Mybatis
#--------------------------------------------------
mybatis.type-aliases-package=com.allpack.rm.dto
mybatis.mapper-locations=mybatis-mapper/*.xml
